development:
  adapter: postgresql
  encoding: unicode
  database: student_manager_development
  pool: 5
  username: smanager

test:
  adapter: postgresql
  encoding: unicode
  database: student_manager_test
  pool: 5
  username: smanager
